webtalk_init -webtalk_dir D:/Yolo_FPGA/Sobel - timing-align/Sobel.sim/sim_1/impl/timing/xsim/xsim.dir/Image_Processor_tb_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec  8 21:40:55 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "94785f87-54bc-4e3b-bbd5-6c8d1220b5a4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "90c70b2b3cdd444e85174ca3a73f0189" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "79" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i9-13900H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2215764426 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "918.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "95504_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4282932543 -regid "" -xml D:/Yolo_FPGA/Sobel - timing-align/Sobel.sim/sim_1/impl/timing/xsim/xsim.dir/Image_Processor_tb_time_impl/webtalk/usage_statistics_ext_xsim.xml -html D:/Yolo_FPGA/Sobel - timing-align/Sobel.sim/sim_1/impl/timing/xsim/xsim.dir/Image_Processor_tb_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm D:/Yolo_FPGA/Sobel - timing-align/Sobel.sim/sim_1/impl/timing/xsim/xsim.dir/Image_Processor_tb_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
