# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Yolo_FPGA/Sobel - timing-align/Sobel.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
# IP: The module: 'c_shift_ram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Yolo_FPGA/Sobel - timing-align/Sobel.gen/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Yolo_FPGA/Sobel - timing-align/Sobel.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
# IP: The module: 'c_shift_ram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Yolo_FPGA/Sobel - timing-align/Sobel.gen/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
